
name: PR validations

on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test
